import {useAppValue} from 'context/AppContext'
import Head from 'next/head'
import useIsMobile from 'hooks/useIsMobile'
import Navbar from 'components/Navbar'
import {BackIcon} from 'components/svgs/Page2/Icons'
import Placa from 'components/Placa'
import Counter from 'components/Counter'
import TabCoberturas from 'components/TabCoberturas'
import Coberturas from 'components/Coberturas'
import Monto from 'components/Monto'
import History from 'components/History'
import cn from 'classnames'
import {useRouter} from 'next/dist/client/router'

export default function Page() {
  const [state] = useAppValue()
  const {isMobile} = useIsMobile()
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Arma tu plan | Hacking challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar white />
      <main className="w-full relative border-t border-[#E4E8F7]">
        <section
          className="w-full 
				flex flex-wrap"
        >
          <article
            className={cn(
              'w-full md:w-[30%] lg:w-[22%]',
              !isMobile && 'bg-mobile',
              isMobile && 'border-b border-[#E4E8F7]',
            )}
          >
            <div className="container_mobile">
              <History />
            </div>
          </article>
          <article className="w-full md:w-[70%] lg:w-[78%] container_mobile">
            <div
              className="w-full md:w-[74%]
						md:ml-[8%] md:mr-[18%] md:my-14
						xl:w-[70%] xl:ml-[10%] xl:mr-[20%]
						flex flex-wrap"
            >
              <section className="w-full lg:w-[65%] xl:w-[63%] md:pr-10 xl:pr-16">
                {!isMobile && (
                  <button
                    className="flex items-center"
                    onClick={() => router.push('/')}
                  >
                    <BackIcon color="#EF3340" />{' '}
                    <span className="text-sm uppercase pl-3">Volver</span>
                  </button>
                )}
                <div className="my-6">
                  <h1 className="text-title text-2xl md:text-4xl mb-2 md:mb-3">
                    {!isMobile ? (
                      <>
                        ¡Hola,{' '}
                        <span className="text-main">
                          {state?.user?.name || 'Loading...'}!
                        </span>
                      </>
                    ) : (
                      'Mira las coberturas'
                    )}
                  </h1>
                  <p>Conoce las coberturas para tu plan</p>
                  <section className="my-10">
                    <article>
                      <Placa />
                      <Counter />
                      <hr className="border-color my-10" />
                      <h3 className="text-title text-xl">
                        Agrega o quita coberturas
                      </h3>
                      {/* List */}
                      <TabCoberturas />
                      <Coberturas />
                    </article>
                  </section>
                </div>
              </section>
              <section className="w-full lg:w-[35%] xl:w-[37%] md:pl-10 xl:pl-16">
                <Monto />
              </section>
            </div>
          </article>
        </section>
      </main>
    </>
  )
}
