import React from 'react'
import Head from 'next/head'
import Navbar from 'components/Navbar'
import useIsMobile from 'hooks/useIsMobile'
import {MainIcon, MainIconMobile} from 'components/svgs/Page3/Icons'
import {useAppValue} from 'context/AppContext'
import {useRouter} from 'next/dist/client/router'

export default function Gracias() {
  const {isMobile} = useIsMobile()
  const [state] = useAppValue()
  const router = useRouter()

  React.useEffect(() => {
    /* eslint-disable */
    if (!state.placa) router.push('/')
  }, [state])
  if (!state.placa)
    return (
      <div>
        <h1>Loading...</h1>
      </div>
    )
  return (
    <div>
      <Head>
        <title>Gracias | Hacking challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar white fixed />
      <main className="w-full h-[100%] relative overflow-hidden">
        <section
          className="w-full 
				flex flex-wrap"
        >
          <article className="relative w-full md:w-[40%] md:h-[100vh] flex items-center bg_gracias sm:bg-[#F7F8FC] md:bg-transparent md:bg-none">
            <div className="absolute md:w-full lg:w-[80%] h-full bg-mobile"></div>
            <div className="container_mobile">
              <div
                className="w-full
							lg:w-[60%] lg:ml-[25%] lg:mr-[15%] mt-32 pb-[45%] md:pb-0 md:mt-0"
              >
                <div className="absolute bottom-0 right-10 md:relative md:bottom-auto md:right-auto">
                  {isMobile ? <MainIconMobile /> : <MainIcon />}
                </div>
              </div>
            </div>
          </article>
          <article className="w-full md:w-[60%] md:h-[100vh] container_mobile flex items-center">
            <div className="w-full md:w-[60%] md:mx-[20%] xl:w-[50%] xl:ml-[10%] xl:mr-[40%] my-12">
              <h1 className="text-title text-2xl md:text-3xl">
                <span className="block text-main">
                  ¡Te damos la bienvenida!
                </span>
                Cuenta con nosotros para proteger tu vehículo
              </h1>
              <p className="mt-6 mb-10">
                Enviaremos la confirmación de compra de tu Plan Vehícular
                Tracking{' '}
                <span className="font-bold">
                  (${state?.amount.toFixed(2)} mensual)
                </span>{' '}
                a tu correo:
                <span className="block text-title font-bold">
                  {state?.user?.email}
                </span>
              </p>
              <button
                className="text-white text-sm uppercase
								bg-main rounded-lg
								px-12 py-4 w-full md:w-auto"
                onClick={() => (location.pathname = '/')}
              >
                cómo usar mi seguro
              </button>
            </div>
          </article>
        </section>
      </main>
      {isMobile && (
        <footer className="py-6 border-t boder-color">
          <section className="container">
            <small className="text-[#A3ABCC] text-xs">
              © 2021 RIMAC Seguros y Reaseguros.
            </small>
          </section>
        </footer>
      )}
    </div>
  )
}
