import Head from 'next/head'
import Navbar from 'components/Navbar'
import BannerIcon from 'components/svgs/BannerIcon'
import BannerIconMobile from 'components/svgs/BannerIconMobile'
import FormHome from 'components/FormHome'
import useIsMobile from 'hooks/useIsMobile'
// import {useAppValue} from 'context/AppContext'

export default function Home() {
  const {isMobile} = useIsMobile()
  return (
    <div>
      <Head>
        <title>Home | Hacking challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="w-full h-[100%] relative overflow-hidden">
        <section
          className="w-full 
				flex flex-wrap"
        >
          <article className="w-full md:w-[40%] md:h-[100vh] bg-mobile md:bg_banner flex items-center">
            <div className="container_mobile">
              <div className="w-full md:w-[60%] md:ml-[25%] md:mr-[15%] my-14">
                <div className="absolute top-[2.5%] right-0 md:relative md:top-auto md:right-auto">
                  {isMobile ? <BannerIconMobile /> : <BannerIcon />}
                </div>
                <div className="w-[70%] md:w-full">
                  <p className="text-xs md:text-base text-title font-bold uppercase">
                    ¡Nuevo!
                  </p>
                  <h1 className="text-[28px] leading-tight md:text-4xl font-normal text-title mt-2 mb-4">
                    Seguro{' '}
                    <span className="text-main">
                      Vehicular <br /> Tracking
                    </span>
                  </h1>
                  <p className="mb-8">
                    Cuentanos donde le haras seguimiento a tu seguro
                  </p>
                </div>
              </div>
            </div>
          </article>
          <aricle className="w-full md:w-[60%] md:h-[100vh] container_mobile flex items-center">
            <div className="w-full md:w-[60%] md:mx-[20%] my-14">
              <h1 className="text-title text-3xl">Déjanos tus datos</h1>
              <FormHome />
            </div>
          </aricle>
        </section>
      </main>
    </div>
  )
}
